#------------------------------------------------------
# Github Actions - Basics
#
# Copyleft (c) by Oleksandr Mukas 2026.
#------------------------------------------------------
name: My-Actions-Basics

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello message
        run: echo "Hello from Testing job"
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: my_testing
    steps:
      - name: Print Hello message
        run: echo "Hello from Deploy job"
          
    
